[2022-09-08T10:33:12.334+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: our_first_dag_v5.second_task scheduled__2021-09-09T00:00:00+00:00 [queued]>
[2022-09-08T10:33:12.455+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: our_first_dag_v5.second_task scheduled__2021-09-09T00:00:00+00:00 [queued]>
[2022-09-08T10:33:12.459+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-09-08T10:33:12.463+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 6
[2022-09-08T10:33:12.467+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-09-08T10:33:12.668+0000] {taskinstance.py:1389} INFO - Executing <Task(BashOperator): second_task> on 2021-09-09 00:00:00+00:00
[2022-09-08T10:33:12.726+0000] {standard_task_runner.py:52} INFO - Started process 3707 to run task
[2022-09-08T10:33:12.788+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v5', 'second_task', 'scheduled__2021-09-09T00:00:00+00:00', '--job-id', '136', '--raw', '--subdir', 'DAGS_FOLDER/example_dags.py', '--cfg-path', '/tmp/tmpsdz6105g', '--error-file', '/tmp/tmp31__bs3e']
[2022-09-08T10:33:12.804+0000] {standard_task_runner.py:80} INFO - Job 136: Subtask second_task
[2022-09-08T10:33:13.221+0000] {task_command.py:371} INFO - Running <TaskInstance: our_first_dag_v5.second_task scheduled__2021-09-09T00:00:00+00:00 [running]> on host c56eb7ae2624
[2022-09-08T10:33:22.243+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=our_first_dag_v5
AIRFLOW_CTX_TASK_ID=second_task
AIRFLOW_CTX_EXECUTION_DATE=2021-09-09T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-09-09T00:00:00+00:00
[2022-09-08T10:33:22.253+0000] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-09-08T10:33:22.257+0000] {subprocess.py:74} INFO - Running command: ['/bin/bash', '-c', 'Dm log nhu lon']
[2022-09-08T10:33:22.373+0000] {subprocess.py:85} INFO - Output:
[2022-09-08T10:33:22.417+0000] {subprocess.py:92} INFO - /bin/bash: line 1: Dm: command not found
[2022-09-08T10:33:22.418+0000] {subprocess.py:96} INFO - Command exited with return code 127
[2022-09-08T10:33:22.509+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-09-08T10:33:22.540+0000] {taskinstance.py:1412} INFO - Marking task as UP_FOR_RETRY. dag_id=our_first_dag_v5, task_id=second_task, execution_date=20210909T000000, start_date=20220908T103312, end_date=20220908T103322
[2022-09-08T10:33:22.650+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 136 for task second_task (Bash command failed. The command returned a non-zero exit code 127.; 3707)
[2022-09-08T10:33:23.247+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-09-08T10:33:23.434+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
