[2022-09-08T11:10:50.196+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: first_dag_v11.second_task scheduled__2022-09-07T00:00:00+00:00 [queued]>
[2022-09-08T11:10:50.202+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: first_dag_v11.second_task scheduled__2022-09-07T00:00:00+00:00 [queued]>
[2022-09-08T11:10:50.203+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-09-08T11:10:50.205+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 6
[2022-09-08T11:10:50.205+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-09-08T11:10:50.213+0000] {taskinstance.py:1389} INFO - Executing <Task(BashOperator): second_task> on 2022-09-07 00:00:00+00:00
[2022-09-08T11:10:50.217+0000] {standard_task_runner.py:52} INFO - Started process 633 to run task
[2022-09-08T11:10:50.220+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'first_dag_v11', 'second_task', 'scheduled__2022-09-07T00:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/example_dags.py', '--cfg-path', '/tmp/tmpf2l4cehg', '--error-file', '/tmp/tmp4ngn60d7']
[2022-09-08T11:10:50.222+0000] {standard_task_runner.py:80} INFO - Job 10: Subtask second_task
[2022-09-08T11:10:50.260+0000] {task_command.py:371} INFO - Running <TaskInstance: first_dag_v11.second_task scheduled__2022-09-07T00:00:00+00:00 [running]> on host e458dbb0fb9f
[2022-09-08T11:10:50.299+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=first_dag_v11
AIRFLOW_CTX_TASK_ID=second_task
AIRFLOW_CTX_EXECUTION_DATE=2022-09-07T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-07T00:00:00+00:00
[2022-09-08T11:10:50.301+0000] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-09-08T11:10:50.302+0000] {subprocess.py:74} INFO - Running command: ['/bin/bash', '-c', 'Dm log nhu lon']
[2022-09-08T11:10:50.311+0000] {subprocess.py:85} INFO - Output:
[2022-09-08T11:10:50.313+0000] {subprocess.py:92} INFO - /bin/bash: line 1: Dm: command not found
[2022-09-08T11:10:50.314+0000] {subprocess.py:96} INFO - Command exited with return code 127
[2022-09-08T11:10:50.326+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-09-08T11:10:50.344+0000] {taskinstance.py:1412} INFO - Marking task as UP_FOR_RETRY. dag_id=first_dag_v11, task_id=second_task, execution_date=20220907T000000, start_date=20220908T111050, end_date=20220908T111050
[2022-09-08T11:10:50.437+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 10 for task second_task (Bash command failed. The command returned a non-zero exit code 127.; 633)
[2022-09-08T11:10:50.475+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-09-08T11:10:50.494+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
