[2022-09-08T10:33:44.618+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: first_dag_v6.first_task scheduled__2021-08-11T00:00:00+00:00 [queued]>
[2022-09-08T10:33:44.627+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: first_dag_v6.first_task scheduled__2021-08-11T00:00:00+00:00 [queued]>
[2022-09-08T10:33:44.628+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-09-08T10:33:44.633+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 6
[2022-09-08T10:33:44.635+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-09-08T10:33:44.649+0000] {taskinstance.py:1389} INFO - Executing <Task(BashOperator): first_task> on 2021-08-11 00:00:00+00:00
[2022-09-08T10:33:44.655+0000] {standard_task_runner.py:52} INFO - Started process 3805 to run task
[2022-09-08T10:33:44.660+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'first_dag_v6', 'first_task', 'scheduled__2021-08-11T00:00:00+00:00', '--job-id', '159', '--raw', '--subdir', 'DAGS_FOLDER/example_dags.py', '--cfg-path', '/tmp/tmpeno5cihx', '--error-file', '/tmp/tmpvaa6lfbs']
[2022-09-08T10:33:44.663+0000] {standard_task_runner.py:80} INFO - Job 159: Subtask first_task
[2022-09-08T10:33:44.722+0000] {task_command.py:371} INFO - Running <TaskInstance: first_dag_v6.first_task scheduled__2021-08-11T00:00:00+00:00 [running]> on host c56eb7ae2624
[2022-09-08T10:33:44.943+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=first_dag_v6
AIRFLOW_CTX_TASK_ID=first_task
AIRFLOW_CTX_EXECUTION_DATE=2021-08-11T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-08-11T00:00:00+00:00
[2022-09-08T10:33:44.944+0000] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-09-08T10:33:44.945+0000] {subprocess.py:74} INFO - Running command: ['/bin/bash', '-c', 'hello day la dinh chi cong']
[2022-09-08T10:33:44.957+0000] {subprocess.py:85} INFO - Output:
[2022-09-08T10:33:44.959+0000] {subprocess.py:92} INFO - /bin/bash: line 1: hello: command not found
[2022-09-08T10:33:44.960+0000] {subprocess.py:96} INFO - Command exited with return code 127
[2022-09-08T10:33:44.972+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-09-08T10:33:44.975+0000] {taskinstance.py:1412} INFO - Marking task as UP_FOR_RETRY. dag_id=first_dag_v6, task_id=first_task, execution_date=20210811T000000, start_date=20220908T103344, end_date=20220908T103344
[2022-09-08T10:33:44.989+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 159 for task first_task (Bash command failed. The command returned a non-zero exit code 127.; 3805)
[2022-09-08T10:33:45.031+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-09-08T10:33:45.065+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
