[2022-09-08T11:05:36.157+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: first_dag_v8.first_task manual__2022-09-08T11:05:35.014949+00:00 [queued]>
[2022-09-08T11:05:36.169+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: first_dag_v8.first_task manual__2022-09-08T11:05:35.014949+00:00 [queued]>
[2022-09-08T11:05:36.170+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-09-08T11:05:36.171+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 6
[2022-09-08T11:05:36.171+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-09-08T11:05:36.178+0000] {taskinstance.py:1389} INFO - Executing <Task(BashOperator): first_task> on 2022-09-08 11:05:35.014949+00:00
[2022-09-08T11:05:36.182+0000] {standard_task_runner.py:52} INFO - Started process 273 to run task
[2022-09-08T11:05:36.184+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'first_dag_v8', 'first_task', 'manual__2022-09-08T11:05:35.014949+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/example_dags.py', '--cfg-path', '/tmp/tmpire2joee', '--error-file', '/tmp/tmp8kzm_6v4']
[2022-09-08T11:05:36.186+0000] {standard_task_runner.py:80} INFO - Job 3: Subtask first_task
[2022-09-08T11:05:36.222+0000] {task_command.py:371} INFO - Running <TaskInstance: first_dag_v8.first_task manual__2022-09-08T11:05:35.014949+00:00 [running]> on host e458dbb0fb9f
[2022-09-08T11:05:36.265+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=first_dag_v8
AIRFLOW_CTX_TASK_ID=first_task
AIRFLOW_CTX_EXECUTION_DATE=2022-09-08T11:05:35.014949+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-08T11:05:35.014949+00:00
[2022-09-08T11:05:36.266+0000] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-09-08T11:05:36.267+0000] {subprocess.py:74} INFO - Running command: ['/bin/bash', '-c', 'hello day la dinh chi cong']
[2022-09-08T11:05:36.274+0000] {subprocess.py:85} INFO - Output:
[2022-09-08T11:05:36.276+0000] {subprocess.py:92} INFO - /bin/bash: line 1: hello: command not found
[2022-09-08T11:05:36.277+0000] {subprocess.py:96} INFO - Command exited with return code 127
[2022-09-08T11:05:36.287+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-09-08T11:05:36.291+0000] {taskinstance.py:1412} INFO - Marking task as UP_FOR_RETRY. dag_id=first_dag_v8, task_id=first_task, execution_date=20220908T110535, start_date=20220908T110536, end_date=20220908T110536
[2022-09-08T11:05:36.451+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 3 for task first_task (Bash command failed. The command returned a non-zero exit code 127.; 273)
[2022-09-08T11:05:36.484+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-09-08T11:05:36.511+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
