[2022-09-08T11:09:10.666+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: first_dag_v10.first_task scheduled__2022-09-07T00:00:00+00:00 [queued]>
[2022-09-08T11:09:10.672+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: first_dag_v10.first_task scheduled__2022-09-07T00:00:00+00:00 [queued]>
[2022-09-08T11:09:10.673+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-09-08T11:09:10.674+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 6
[2022-09-08T11:09:10.675+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-09-08T11:09:10.683+0000] {taskinstance.py:1389} INFO - Executing <Task(BashOperator): first_task> on 2022-09-07 00:00:00+00:00
[2022-09-08T11:09:10.687+0000] {standard_task_runner.py:52} INFO - Started process 512 to run task
[2022-09-08T11:09:10.690+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'first_dag_v10', 'first_task', 'scheduled__2022-09-07T00:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/example_dags.py', '--cfg-path', '/tmp/tmp4bxa4gst', '--error-file', '/tmp/tmp_q3nz2sr']
[2022-09-08T11:09:10.691+0000] {standard_task_runner.py:80} INFO - Job 7: Subtask first_task
[2022-09-08T11:09:10.728+0000] {task_command.py:371} INFO - Running <TaskInstance: first_dag_v10.first_task scheduled__2022-09-07T00:00:00+00:00 [running]> on host e458dbb0fb9f
[2022-09-08T11:09:10.771+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=first_dag_v10
AIRFLOW_CTX_TASK_ID=first_task
AIRFLOW_CTX_EXECUTION_DATE=2022-09-07T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-07T00:00:00+00:00
[2022-09-08T11:09:10.773+0000] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-09-08T11:09:10.774+0000] {subprocess.py:74} INFO - Running command: ['/bin/bash', '-c', 'hello day la dinh chi cong']
[2022-09-08T11:09:10.782+0000] {subprocess.py:85} INFO - Output:
[2022-09-08T11:09:10.783+0000] {subprocess.py:92} INFO - /bin/bash: line 1: hello: command not found
[2022-09-08T11:09:10.785+0000] {subprocess.py:96} INFO - Command exited with return code 127
[2022-09-08T11:09:10.799+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-09-08T11:09:10.803+0000] {taskinstance.py:1412} INFO - Marking task as UP_FOR_RETRY. dag_id=first_dag_v10, task_id=first_task, execution_date=20220907T000000, start_date=20220908T110910, end_date=20220908T110910
[2022-09-08T11:09:11.018+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 7 for task first_task (Bash command failed. The command returned a non-zero exit code 127.; 512)
[2022-09-08T11:09:11.064+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-09-08T11:09:11.118+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
