[2022-09-08T10:33:20.767+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: our_first_dag_v5.first_task scheduled__2021-09-17T00:00:00+00:00 [queued]>
[2022-09-08T10:33:21.086+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: our_first_dag_v5.first_task scheduled__2021-09-17T00:00:00+00:00 [queued]>
[2022-09-08T10:33:21.088+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-09-08T10:33:21.093+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 6
[2022-09-08T10:33:21.094+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-09-08T10:33:21.397+0000] {taskinstance.py:1389} INFO - Executing <Task(BashOperator): first_task> on 2021-09-17 00:00:00+00:00
[2022-09-08T10:33:21.465+0000] {standard_task_runner.py:52} INFO - Started process 3724 to run task
[2022-09-08T10:33:21.515+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v5', 'first_task', 'scheduled__2021-09-17T00:00:00+00:00', '--job-id', '145', '--raw', '--subdir', 'DAGS_FOLDER/example_dags.py', '--cfg-path', '/tmp/tmpk2wykji0', '--error-file', '/tmp/tmpakr42fjh']
[2022-09-08T10:33:21.550+0000] {standard_task_runner.py:80} INFO - Job 145: Subtask first_task
[2022-09-08T10:33:21.934+0000] {task_command.py:371} INFO - Running <TaskInstance: our_first_dag_v5.first_task scheduled__2021-09-17T00:00:00+00:00 [running]> on host c56eb7ae2624
[2022-09-08T10:33:24.054+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=our_first_dag_v5
AIRFLOW_CTX_TASK_ID=first_task
AIRFLOW_CTX_EXECUTION_DATE=2021-09-17T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-09-17T00:00:00+00:00
[2022-09-08T10:33:24.067+0000] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-09-08T10:33:24.069+0000] {subprocess.py:74} INFO - Running command: ['/bin/bash', '-c', 'hello day la dinh chi cong']
[2022-09-08T10:33:24.115+0000] {subprocess.py:85} INFO - Output:
[2022-09-08T10:33:24.117+0000] {subprocess.py:92} INFO - /bin/bash: line 1: hello: command not found
[2022-09-08T10:33:24.118+0000] {subprocess.py:96} INFO - Command exited with return code 127
[2022-09-08T10:33:24.152+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-09-08T10:33:24.162+0000] {taskinstance.py:1412} INFO - Marking task as UP_FOR_RETRY. dag_id=our_first_dag_v5, task_id=first_task, execution_date=20210917T000000, start_date=20220908T103320, end_date=20220908T103324
[2022-09-08T10:33:24.197+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 145 for task first_task (Bash command failed. The command returned a non-zero exit code 127.; 3724)
[2022-09-08T10:33:24.282+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-09-08T10:33:24.346+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
