[2022-09-08T10:33:44.330+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: first_dag_v6.first_task scheduled__2021-08-10T00:00:00+00:00 [queued]>
[2022-09-08T10:33:44.356+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: first_dag_v6.first_task scheduled__2021-08-10T00:00:00+00:00 [queued]>
[2022-09-08T10:33:44.359+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-09-08T10:33:44.362+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 6
[2022-09-08T10:33:44.363+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-09-08T10:33:44.388+0000] {taskinstance.py:1389} INFO - Executing <Task(BashOperator): first_task> on 2021-08-10 00:00:00+00:00
[2022-09-08T10:33:44.397+0000] {standard_task_runner.py:52} INFO - Started process 3802 to run task
[2022-09-08T10:33:44.406+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'first_dag_v6', 'first_task', 'scheduled__2021-08-10T00:00:00+00:00', '--job-id', '158', '--raw', '--subdir', 'DAGS_FOLDER/example_dags.py', '--cfg-path', '/tmp/tmpp8_41hem', '--error-file', '/tmp/tmpbn8lh_bh']
[2022-09-08T10:33:44.415+0000] {standard_task_runner.py:80} INFO - Job 158: Subtask first_task
[2022-09-08T10:33:44.504+0000] {task_command.py:371} INFO - Running <TaskInstance: first_dag_v6.first_task scheduled__2021-08-10T00:00:00+00:00 [running]> on host c56eb7ae2624
[2022-09-08T10:33:44.722+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=first_dag_v6
AIRFLOW_CTX_TASK_ID=first_task
AIRFLOW_CTX_EXECUTION_DATE=2021-08-10T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-08-10T00:00:00+00:00
[2022-09-08T10:33:44.724+0000] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-09-08T10:33:44.726+0000] {subprocess.py:74} INFO - Running command: ['/bin/bash', '-c', 'hello day la dinh chi cong']
[2022-09-08T10:33:44.749+0000] {subprocess.py:85} INFO - Output:
[2022-09-08T10:33:44.756+0000] {subprocess.py:92} INFO - /bin/bash: line 1: hello: command not found
[2022-09-08T10:33:44.757+0000] {subprocess.py:96} INFO - Command exited with return code 127
[2022-09-08T10:33:44.773+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-09-08T10:33:44.781+0000] {taskinstance.py:1412} INFO - Marking task as UP_FOR_RETRY. dag_id=first_dag_v6, task_id=first_task, execution_date=20210810T000000, start_date=20220908T103344, end_date=20220908T103344
[2022-09-08T10:33:44.797+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 158 for task first_task (Bash command failed. The command returned a non-zero exit code 127.; 3802)
[2022-09-08T10:33:44.822+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-09-08T10:33:44.858+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
