[2022-09-08T11:08:11.387+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: first_dag_v9.first_task manual__2022-09-08T11:08:10.792690+00:00 [queued]>
[2022-09-08T11:08:11.394+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: first_dag_v9.first_task manual__2022-09-08T11:08:10.792690+00:00 [queued]>
[2022-09-08T11:08:11.395+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-09-08T11:08:11.396+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 6
[2022-09-08T11:08:11.397+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-09-08T11:08:11.405+0000] {taskinstance.py:1389} INFO - Executing <Task(BashOperator): first_task> on 2022-09-08 11:08:10.792690+00:00
[2022-09-08T11:08:11.409+0000] {standard_task_runner.py:52} INFO - Started process 438 to run task
[2022-09-08T11:08:11.411+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'first_dag_v9', 'first_task', 'manual__2022-09-08T11:08:10.792690+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/example_dags.py', '--cfg-path', '/tmp/tmp60xb3n9h', '--error-file', '/tmp/tmp0woq_v04']
[2022-09-08T11:08:11.413+0000] {standard_task_runner.py:80} INFO - Job 5: Subtask first_task
[2022-09-08T11:08:11.451+0000] {task_command.py:371} INFO - Running <TaskInstance: first_dag_v9.first_task manual__2022-09-08T11:08:10.792690+00:00 [running]> on host e458dbb0fb9f
[2022-09-08T11:08:11.491+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=first_dag_v9
AIRFLOW_CTX_TASK_ID=first_task
AIRFLOW_CTX_EXECUTION_DATE=2022-09-08T11:08:10.792690+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-08T11:08:10.792690+00:00
[2022-09-08T11:08:11.492+0000] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-09-08T11:08:11.493+0000] {subprocess.py:74} INFO - Running command: ['/bin/bash', '-c', 'hello day la dinh chi cong']
[2022-09-08T11:08:11.501+0000] {subprocess.py:85} INFO - Output:
[2022-09-08T11:08:11.503+0000] {subprocess.py:92} INFO - /bin/bash: line 1: hello: command not found
[2022-09-08T11:08:11.504+0000] {subprocess.py:96} INFO - Command exited with return code 127
[2022-09-08T11:08:11.515+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-09-08T11:08:11.519+0000] {taskinstance.py:1412} INFO - Marking task as UP_FOR_RETRY. dag_id=first_dag_v9, task_id=first_task, execution_date=20220908T110810, start_date=20220908T110811, end_date=20220908T110811
[2022-09-08T11:08:11.659+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 5 for task first_task (Bash command failed. The command returned a non-zero exit code 127.; 438)
[2022-09-08T11:08:11.706+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-09-08T11:08:11.731+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
