[2022-09-08T10:33:13.502+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: our_first_dag_v5.second_task scheduled__2021-09-08T00:00:00+00:00 [queued]>
[2022-09-08T10:33:13.754+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: our_first_dag_v5.second_task scheduled__2021-09-08T00:00:00+00:00 [queued]>
[2022-09-08T10:33:13.759+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-09-08T10:33:13.761+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 6
[2022-09-08T10:33:13.764+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-09-08T10:33:13.980+0000] {taskinstance.py:1389} INFO - Executing <Task(BashOperator): second_task> on 2021-09-08 00:00:00+00:00
[2022-09-08T10:33:14.065+0000] {standard_task_runner.py:52} INFO - Started process 3711 to run task
[2022-09-08T10:33:14.129+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v5', 'second_task', 'scheduled__2021-09-08T00:00:00+00:00', '--job-id', '137', '--raw', '--subdir', 'DAGS_FOLDER/example_dags.py', '--cfg-path', '/tmp/tmpj28b5i8v', '--error-file', '/tmp/tmpbnnj0uwz']
[2022-09-08T10:33:14.166+0000] {standard_task_runner.py:80} INFO - Job 137: Subtask second_task
[2022-09-08T10:33:14.865+0000] {task_command.py:371} INFO - Running <TaskInstance: our_first_dag_v5.second_task scheduled__2021-09-08T00:00:00+00:00 [running]> on host c56eb7ae2624
[2022-09-08T10:33:22.387+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=our_first_dag_v5
AIRFLOW_CTX_TASK_ID=second_task
AIRFLOW_CTX_EXECUTION_DATE=2021-09-08T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-09-08T00:00:00+00:00
[2022-09-08T10:33:22.403+0000] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-09-08T10:33:22.414+0000] {subprocess.py:74} INFO - Running command: ['/bin/bash', '-c', 'Dm log nhu lon']
[2022-09-08T10:33:22.641+0000] {subprocess.py:85} INFO - Output:
[2022-09-08T10:33:22.654+0000] {subprocess.py:92} INFO - /bin/bash: line 1: Dm: command not found
[2022-09-08T10:33:22.687+0000] {subprocess.py:96} INFO - Command exited with return code 127
[2022-09-08T10:33:22.746+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-09-08T10:33:22.777+0000] {taskinstance.py:1412} INFO - Marking task as UP_FOR_RETRY. dag_id=our_first_dag_v5, task_id=second_task, execution_date=20210908T000000, start_date=20220908T103313, end_date=20220908T103322
[2022-09-08T10:33:22.913+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 137 for task second_task (Bash command failed. The command returned a non-zero exit code 127.; 3711)
[2022-09-08T10:33:23.567+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-09-08T10:33:23.741+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
