[2022-09-08T10:33:42.805+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: first_dag_v6.first_task scheduled__2021-08-02T00:00:00+00:00 [queued]>
[2022-09-08T10:33:42.824+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: first_dag_v6.first_task scheduled__2021-08-02T00:00:00+00:00 [queued]>
[2022-09-08T10:33:42.826+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-09-08T10:33:42.827+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 6
[2022-09-08T10:33:42.828+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-09-08T10:33:42.854+0000] {taskinstance.py:1389} INFO - Executing <Task(BashOperator): first_task> on 2021-08-02 00:00:00+00:00
[2022-09-08T10:33:42.859+0000] {standard_task_runner.py:52} INFO - Started process 3780 to run task
[2022-09-08T10:33:42.867+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'first_dag_v6', 'first_task', 'scheduled__2021-08-02T00:00:00+00:00', '--job-id', '150', '--raw', '--subdir', 'DAGS_FOLDER/example_dags.py', '--cfg-path', '/tmp/tmpegqi_kf8', '--error-file', '/tmp/tmpvfzzttrh']
[2022-09-08T10:33:42.874+0000] {standard_task_runner.py:80} INFO - Job 150: Subtask first_task
[2022-09-08T10:33:42.963+0000] {task_command.py:371} INFO - Running <TaskInstance: first_dag_v6.first_task scheduled__2021-08-02T00:00:00+00:00 [running]> on host c56eb7ae2624
[2022-09-08T10:33:43.380+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=first_dag_v6
AIRFLOW_CTX_TASK_ID=first_task
AIRFLOW_CTX_EXECUTION_DATE=2021-08-02T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-08-02T00:00:00+00:00
[2022-09-08T10:33:43.382+0000] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-09-08T10:33:43.384+0000] {subprocess.py:74} INFO - Running command: ['/bin/bash', '-c', 'hello day la dinh chi cong']
[2022-09-08T10:33:43.401+0000] {subprocess.py:85} INFO - Output:
[2022-09-08T10:33:43.406+0000] {subprocess.py:92} INFO - /bin/bash: line 1: hello: command not found
[2022-09-08T10:33:43.411+0000] {subprocess.py:96} INFO - Command exited with return code 127
[2022-09-08T10:33:43.473+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-09-08T10:33:43.478+0000] {taskinstance.py:1412} INFO - Marking task as UP_FOR_RETRY. dag_id=first_dag_v6, task_id=first_task, execution_date=20210802T000000, start_date=20220908T103342, end_date=20220908T103343
[2022-09-08T10:33:43.495+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 150 for task first_task (Bash command failed. The command returned a non-zero exit code 127.; 3780)
[2022-09-08T10:33:43.533+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-09-08T10:33:43.710+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
